- hosts: local
  connection: local
  vars:
    region: eu-central-1
  tasks:
    - name: Get EC2 info
      ec2_instance_facts:
        region: "{{ region }}"
      register: ec2
    - debug: var=ec2

    - name: Shut Down EC2 Instances
      ec2:
        instance_ids: '{{ item.instance_id }}'
        state: stopped
        region: "{{ region }}"
      with_items: "{{ ec2.instances }}"

